baseURL = "https://www.spmalloy.com"
copyright = "Copyright 2022 Sean Malloy, all rights reserved"
languageCode = "en-us"
title = "Sean Malloy"
theme = "minimal"

[params]
    author = "Sean Malloy"
    description = "Sean Malloy's website. Unix, Linux, code"
    githubUsername = "seanmalloy"
    accent = "blue"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/posts/"
    name = "Posts"
    weight = 2

#[[menu.main]]
#    url = "/project/"
#    name = "Projects"
#    weight = 3

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:spinelli85@gmail.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/seanmalloy/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/spmalloy/"
    name = "twitter"
    weight = 3
