baseURL = "https://www.spmalloy.com"
title = "Sean Malloy"
theme = "hugo-coder"
languageCode = "en-us"
defaultcontentlanguage = "en"
copyright = "Copyright 2022 Sean Malloy, all rights reserved"

paginate = 20
pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
    author = "Sean Malloy"
    info = "Linux, Code, Maker"
    description = "Sean Malloy's personal website"
    keywords = "blog,personal"
    avatarurl = "images/avatar.png"
    #gravatar = "john.doe@example.com"
    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"
    since = 2016
    enableTwemoji = true
    colorScheme = "auto"
    hidecolorschemetoggle = false

[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"
    author = "authors"

# Social links
[[params.social]]
    name = "Github"
    icon = "fa fa-github fa-2x"
    weight = 1
    url = "https://github.com/seanmalloy/"
[[params.social]]
    name = "Twitter"
    icon = "fa fa-twitter fa-2x"
    weight = 3
    url = "https://twitter.com/spmalloy/"
[[params.social]]
    name = "LinkedIn"
    icon = "fa fa-2x fa-linkedin"
    weight = 4
    url = "https://www.linkedin.com/in/spmalloy"
[[params.social]]
    name = "Mastodon"
    icon = "fa fa-2x fa-mastodon"
    weight = 4
    url = "https://techhub.social/@spmalloy"
[[params.social]]
    name = "Keybase"
    icon = "fa fa-2x fa-keybase"
    weight = 4
    url = "https://keybase.io/spmalloy"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "posts/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "about/"

